### ISSUE TITLE
Why is arc_angle limited to 180°?

### ISSUE THREAD

**Issue by haath** [defold/sample-lights-and-shadows#4]
The README says:

> Arc angle of the lightsource. Can be used to generate a cone of light up to an arc angle of 180 degrees. Anything above 180 degrees will result in a full circle.

However simply removing this branch from the `update_angle()` function in `lightsource.script#33`, and setting an `arc_angle` larger than `180°` works fine for me:

```lua
if arc_angle > 180 then
    x = 0
    y = 180
    z = 0
    w = -180
else
```

![image](https://user-images.githubusercontent.com/29335643/152635532-b46446f1-79c1-4e89-ad82-36f9a345166f.png)

So why is this limitation of `180°` in place?

Let me know if you think it can be removed and I'll make a PR :)

**Comment by britzl** [comment]
I've included this in an update of the master branch. Thanks.
